import type {
  CatalogEntry,
  Exercise,
  Programme,
  RotationSlot,
  Settings,
  Template,
} from './types';

/**
 * Seed rows use stable slug ids (not random UUIDs) so that an export from one
 * device merges cleanly into another device's seeded database instead of
 * duplicating the whole programme. User-created rows use crypto.randomUUID().
 */

/** The id of the programme the four stock days belong to. Stable forever. */
export const SEED_PROGRAMME_ID = 'prog_upper_lower';

export const SEED_TEMPLATES: Template[] = [
  { id: 'lowerA', programmeId: SEED_PROGRAMME_ID, name: 'Lower A', tags: ['lower', 'legs'], order: 0, archived: false },
  { id: 'upperA', programmeId: SEED_PROGRAMME_ID, name: 'Upper A', tags: ['upper'], order: 1, archived: false },
  { id: 'lowerB', programmeId: SEED_PROGRAMME_ID, name: 'Lower B', tags: ['lower', 'legs'], order: 2, archived: false },
  { id: 'upperB', programmeId: SEED_PROGRAMME_ID, name: 'Upper B', tags: ['upper'], order: 3, archived: false },
];

/** Lower A → Upper A → rest → Lower B → Upper B → rest → rest. */
export const SEED_ROTATION: RotationSlot[] = [
  { templateId: 'lowerA' },
  { templateId: 'upperA' },
  { rest: true },
  { templateId: 'lowerB' },
  { templateId: 'upperB' },
  { rest: true },
  { rest: true },
];

/**
 * The stock programme row. `createdAt` is stamped when it is written, so a
 * fresh install and a v2 upgrade both get a sensible timestamp.
 */
export function seedProgramme(createdAt = Date.now()): Programme {
  return {
    id: SEED_PROGRAMME_ID,
    name: 'Upper / Lower',
    rotation: SEED_ROTATION.map((slot) => ({ ...slot })),
    active: true,
    createdAt,
    archived: false,
  };
}

export const DEFAULT_SETTINGS: Settings = {
  id: 'settings',
  restPrimary: 120,
  restAccessory: 90,
  units: 'kg',
  keepAwake: true,
  barWeight: 20,
  plates: [25, 20, 15, 10, 5, 2.5, 1.25],
  setsPerMuscleTarget: { min: 10, max: 20 },
};

/* ----------------------------------------------------------------- catalogue */

/**
 * The stock exercise catalogue: every movement the seeded programme uses, plus
 * the common alternatives you would swap one for. Ids are `cat_<slug>` and are
 * stable forever — programme rows and session snapshots point at them.
 *
 * Tagging convention: an entry carries its upper/lower tag, its push/pull/legs
 * tag and its body-part tag (deduplicated — `legs` serves as both). The two
 * exceptions are movements that belong to no split: `pattern: 'conditioning'`
 * entries are tagged `['cardio']` and `pattern: 'core'` entries `['core']`,
 * because abs and rowing get trained on whichever day you like.
 */
export const SEED_CATALOG: CatalogEntry[] = [
  // ---------------------------------------------------------- lower body
  {
    id: 'cat_hack_squat',
    name: 'Hack squat',
    primary: ['quads'],
    secondary: ['glutes', 'adductors'],
    equipment: 'machine',
    pattern: 'squat',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
    notes: 'Feet ahead and wide biases glutes and adductors.',
  },
  {
    id: 'cat_leg_press',
    name: 'Leg press',
    primary: ['quads'],
    secondary: ['glutes', 'adductors'],
    equipment: 'machine',
    pattern: 'squat',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_back_squat',
    name: 'Back squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'hamstrings', 'lower_back', 'core'],
    equipment: 'barbell',
    pattern: 'squat',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_front_squat',
    name: 'Front squat',
    primary: ['quads'],
    secondary: ['glutes', 'core', 'upper_back'],
    equipment: 'barbell',
    pattern: 'squat',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_leg_extension',
    name: 'Leg extension',
    primary: ['quads'],
    secondary: [],
    equipment: 'machine',
    pattern: 'isolation',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_leg_curl',
    name: 'Leg curl',
    primary: ['hamstrings'],
    secondary: ['calves'],
    equipment: 'machine',
    pattern: 'isolation',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_barbell_deadlift',
    name: 'Barbell deadlift',
    primary: ['hamstrings', 'glutes', 'lower_back'],
    secondary: ['quads', 'upper_back', 'forearms'],
    equipment: 'barbell',
    pattern: 'hinge',
    unilateral: false,
    tags: ['lower', 'legs', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_romanian_deadlift',
    name: 'Romanian deadlift',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back', 'forearms'],
    equipment: 'barbell',
    pattern: 'hinge',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_seated_db_good_morning',
    name: 'Seated DB good morning',
    primary: ['lower_back'],
    secondary: ['hamstrings', 'glutes', 'core'],
    equipment: 'dumbbell',
    pattern: 'hinge',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_unilateral_hip_thrust',
    name: 'Unilateral floor hip thrust',
    primary: ['glutes'],
    secondary: ['hamstrings', 'core'],
    equipment: 'bodyweight',
    pattern: 'hinge',
    unilateral: true,
    tags: ['lower', 'legs'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_barbell_hip_thrust',
    name: 'Barbell hip thrust',
    primary: ['glutes'],
    secondary: ['hamstrings', 'quads'],
    equipment: 'barbell',
    pattern: 'hinge',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_bulgarian_split_squat',
    name: 'Bulgarian split squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'hamstrings'],
    equipment: 'dumbbell',
    pattern: 'lunge',
    unilateral: true,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_walking_lunge',
    name: 'Walking lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors', 'calves'],
    equipment: 'dumbbell',
    pattern: 'lunge',
    unilateral: true,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_seated_abduction',
    name: 'Seated abduction',
    primary: ['abductors'],
    secondary: ['glutes'],
    equipment: 'band',
    pattern: 'isolation',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'band',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_calf_raises',
    name: 'Calf raises',
    primary: ['calves'],
    secondary: [],
    equipment: 'machine',
    pattern: 'isolation',
    unilateral: false,
    tags: ['lower', 'legs'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },

  // ---------------------------------------------------- upper body — push
  {
    id: 'cat_db_incline_bench',
    name: 'DB incline bench',
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    equipment: 'dumbbell',
    pattern: 'horizontal_push',
    unilateral: false,
    tags: ['upper', 'push', 'chest'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_db_flat_bench',
    name: 'DB flat bench',
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    equipment: 'dumbbell',
    pattern: 'horizontal_push',
    unilateral: false,
    tags: ['upper', 'push', 'chest'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_barbell_bench_press',
    name: 'Barbell bench press',
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    equipment: 'barbell',
    pattern: 'horizontal_push',
    unilateral: false,
    tags: ['upper', 'push', 'chest'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_barbell_incline_bench',
    name: 'Barbell incline bench',
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    equipment: 'barbell',
    pattern: 'horizontal_push',
    unilateral: false,
    tags: ['upper', 'push', 'chest'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_cable_fly',
    name: 'Cable fly',
    primary: ['chest'],
    secondary: ['front_delts'],
    equipment: 'cable',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'push', 'chest'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_dips',
    name: 'Dips',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
    equipment: 'bodyweight',
    pattern: 'horizontal_push',
    unilateral: false,
    tags: ['upper', 'push', 'chest'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_seated_db_ohp',
    name: 'Seated DB OHP',
    primary: ['front_delts'],
    secondary: ['side_delts', 'triceps'],
    equipment: 'dumbbell',
    pattern: 'vertical_push',
    unilateral: false,
    tags: ['upper', 'push', 'shoulders'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_db_laterals',
    name: 'DB laterals',
    primary: ['side_delts'],
    secondary: [],
    equipment: 'dumbbell',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'push', 'shoulders'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_cable_lateral_raise',
    name: 'Cable lateral raise',
    primary: ['side_delts'],
    secondary: [],
    equipment: 'cable',
    pattern: 'isolation',
    unilateral: true,
    tags: ['upper', 'push', 'shoulders'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_pushdowns',
    name: 'Pushdowns',
    primary: ['triceps'],
    secondary: [],
    equipment: 'cable',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'push', 'arms'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_skull_crushers',
    name: 'Skull crushers',
    primary: ['triceps'],
    secondary: [],
    equipment: 'barbell',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'push', 'arms'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },

  // ---------------------------------------------------- upper body — pull
  {
    id: 'cat_seated_row',
    name: 'Seated row',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'forearms'],
    equipment: 'machine',
    pattern: 'horizontal_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_barbell_row',
    name: 'Barbell row',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'lower_back'],
    equipment: 'barbell',
    pattern: 'horizontal_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_hammer_pulldown',
    name: 'Hammer pulldown',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    equipment: 'machine',
    pattern: 'vertical_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_unilateral_pulldown',
    name: 'Unilateral pulldown',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    equipment: 'machine',
    pattern: 'vertical_pull',
    unilateral: true,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_lat_pulldown',
    name: 'Lat pulldown',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    equipment: 'cable',
    pattern: 'vertical_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_pull_up',
    name: 'Pull-up',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back', 'core'],
    equipment: 'bodyweight',
    pattern: 'vertical_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_chin_up',
    name: 'Chin-up',
    primary: ['lats', 'biceps'],
    secondary: ['upper_back', 'core'],
    equipment: 'bodyweight',
    pattern: 'vertical_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_straight_arm_pulldown',
    name: 'Cable straight-arm pulldown',
    primary: ['lats'],
    secondary: ['triceps', 'core'],
    equipment: 'cable',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'pull', 'back'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_machine_reverse_fly',
    name: 'Machine reverse fly',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    equipment: 'machine',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'pull', 'shoulders'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_face_pull',
    name: 'Face pull',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    equipment: 'cable',
    pattern: 'horizontal_pull',
    unilateral: false,
    tags: ['upper', 'pull', 'shoulders'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_db_curls',
    name: 'DB curls',
    primary: ['biceps'],
    secondary: ['forearms'],
    equipment: 'dumbbell',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'pull', 'arms'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_incline_db_curl',
    name: 'Incline DB curl',
    primary: ['biceps'],
    secondary: ['forearms'],
    equipment: 'dumbbell',
    pattern: 'isolation',
    unilateral: false,
    tags: ['upper', 'pull', 'arms'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_farmers_walk',
    name: "Farmer's walk",
    primary: ['forearms'],
    secondary: ['upper_back', 'core', 'quads'],
    equipment: 'dumbbell',
    pattern: 'carry',
    unilateral: false,
    tags: ['upper', 'pull', 'arms'],
    defaultUnit: 'kg_side',
    defaultMeasure: 'laps',
  },

  // ---------------------------------------------------------------- core
  {
    id: 'cat_pallof_press',
    name: 'Pallof press in/out',
    primary: ['core'],
    secondary: ['front_delts'],
    equipment: 'cable',
    pattern: 'core',
    unilateral: true,
    tags: ['core'],
    defaultUnit: 'kg_total',
    defaultMeasure: 'reps',
  },
  {
    id: 'cat_half_side_plank',
    name: 'Half side plank',
    primary: ['core'],
    secondary: ['abductors'],
    equipment: 'bodyweight',
    pattern: 'core',
    unilateral: true,
    tags: ['core'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'seconds',
  },
  {
    id: 'cat_plank',
    name: 'Plank',
    primary: ['core'],
    secondary: ['front_delts'],
    equipment: 'bodyweight',
    pattern: 'core',
    unilateral: false,
    tags: ['core'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'seconds',
  },
  {
    id: 'cat_single_leg_raises',
    name: 'Single-leg raises',
    primary: ['core'],
    secondary: ['quads'],
    equipment: 'bodyweight',
    pattern: 'core',
    unilateral: true,
    tags: ['core'],
    defaultUnit: 'bodyweight',
    defaultMeasure: 'reps',
  },

  // -------------------------------------------------------- conditioning
  {
    id: 'cat_row_1km',
    name: 'Row 1 km',
    primary: ['quads', 'upper_back'],
    secondary: ['lats', 'hamstrings', 'biceps', 'core'],
    equipment: 'machine',
    pattern: 'conditioning',
    unilateral: false,
    tags: ['cardio'],
    defaultUnit: 'none',
    defaultMeasure: 'seconds',
  },
];

/* ----------------------------------------------------------------- programme */

type SeedExercise = Omit<
  Exercise,
  'order' | 'measure' | 'perSide' | 'archived' | 'catalogId'
> &
  Partial<Pick<Exercise, 'measure' | 'perSide'>> & { catalogId: string };

const raw: SeedExercise[] = [
  // ---------------- Lower A — quad-led ----------------
  { id: 'ex_hack_squat', catalogId: 'cat_hack_squat', templateId: 'lowerA', name: 'Hack squat (feet ahead, wide)', sets: 4, repMin: 8, repMax: 10, unit: 'kg_total', increment: 5, type: 'primary' },
  { id: 'ex_leg_press', catalogId: 'cat_leg_press', templateId: 'lowerA', name: 'Leg press', sets: 3, repMin: 12, repMax: 12, unit: 'kg_total', increment: 5, type: 'primary' },
  { id: 'ex_leg_curl_a', catalogId: 'cat_leg_curl', templateId: 'lowerA', name: 'Leg curl', sets: 4, repMin: 10, repMax: 10, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_uni_hip_thrust', catalogId: 'cat_unilateral_hip_thrust', templateId: 'lowerA', name: 'Unilateral floor hip thrust', sets: 3, repMin: 15, repMax: 15, unit: 'bodyweight', increment: 0, type: 'accessory', perSide: true },
  { id: 'ex_seated_abduction', catalogId: 'cat_seated_abduction', templateId: 'lowerA', name: 'Seated abduction (band)', sets: 3, repMin: 25, repMax: 25, unit: 'band', increment: 0, type: 'accessory' },
  { id: 'ex_pallof_press', catalogId: 'cat_pallof_press', templateId: 'lowerA', name: 'Pallof press in/out', sets: 3, repMin: 10, repMax: 10, unit: 'kg_total', increment: 2.5, type: 'accessory', perSide: true },
  { id: 'ex_calf_raises_a', catalogId: 'cat_calf_raises', templateId: 'lowerA', name: 'Calf raises', sets: 3, repMin: 20, repMax: 30, unit: 'kg_total', increment: 2.5, type: 'accessory' },

  // ---------------- Upper A — push-led ----------------
  { id: 'ex_db_incline_bench', catalogId: 'cat_db_incline_bench', templateId: 'upperA', name: 'DB incline bench', sets: 4, repMin: 8, repMax: 10, unit: 'kg_side', increment: 2.5, type: 'primary' },
  { id: 'ex_seated_row', catalogId: 'cat_seated_row', templateId: 'upperA', name: 'Seated row', sets: 4, repMin: 12, repMax: 12, unit: 'kg_total', increment: 5, type: 'primary' },
  { id: 'ex_seated_db_ohp', catalogId: 'cat_seated_db_ohp', templateId: 'upperA', name: 'Seated DB OHP', sets: 3, repMin: 10, repMax: 10, unit: 'kg_side', increment: 2.5, type: 'accessory' },
  { id: 'ex_hammer_pulldown', catalogId: 'cat_hammer_pulldown', templateId: 'upperA', name: 'Hammer pulldown', sets: 3, repMin: 12, repMax: 12, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_db_laterals', catalogId: 'cat_db_laterals', templateId: 'upperA', name: 'DB laterals', sets: 3, repMin: 15, repMax: 15, unit: 'kg_side', increment: 1, type: 'accessory' },
  { id: 'ex_pushdowns', catalogId: 'cat_pushdowns', templateId: 'upperA', name: 'Pushdowns', sets: 3, repMin: 15, repMax: 15, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_half_side_plank', catalogId: 'cat_half_side_plank', templateId: 'upperA', name: 'Half side plank', sets: 3, repMin: 45, repMax: 45, unit: 'bodyweight', increment: 0, type: 'accessory', measure: 'seconds', perSide: true },

  // ---------------- Lower B — hinge-led ----------------
  { id: 'ex_deadlift', catalogId: 'cat_barbell_deadlift', templateId: 'lowerB', name: 'Barbell deadlift', sets: 4, repMin: 6, repMax: 8, unit: 'kg_total', increment: 5, type: 'primary' },
  { id: 'ex_leg_extension', catalogId: 'cat_leg_extension', templateId: 'lowerB', name: 'Leg extension', sets: 3, repMin: 15, repMax: 15, unit: 'kg_total', increment: 5, type: 'primary' },
  { id: 'ex_seated_db_good_morning', catalogId: 'cat_seated_db_good_morning', templateId: 'lowerB', name: 'Seated DB good morning', sets: 3, repMin: 10, repMax: 10, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_leg_curl_b', catalogId: 'cat_leg_curl', templateId: 'lowerB', name: 'Leg curl', sets: 3, repMin: 12, repMax: 12, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_single_leg_raises', catalogId: 'cat_single_leg_raises', templateId: 'lowerB', name: 'Single-leg raises', sets: 3, repMin: 15, repMax: 15, unit: 'bodyweight', increment: 0, type: 'accessory', perSide: true },
  { id: 'ex_calf_raises_b', catalogId: 'cat_calf_raises', templateId: 'lowerB', name: 'Calf raises', sets: 3, repMin: 20, repMax: 30, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_row_1km_b', catalogId: 'cat_row_1km', templateId: 'lowerB', name: 'Row 1 km', sets: 1, repMin: 0, repMax: 0, unit: 'none', increment: 0, type: 'conditioning', measure: 'seconds' },

  // ---------------- Upper B — pull-led ----------------
  { id: 'ex_uni_pulldown', catalogId: 'cat_unilateral_pulldown', templateId: 'upperB', name: 'Unilateral pulldown', sets: 4, repMin: 10, repMax: 10, unit: 'kg_total', increment: 5, type: 'primary', perSide: true },
  { id: 'ex_db_flat_bench', catalogId: 'cat_db_flat_bench', templateId: 'upperB', name: 'DB flat bench', sets: 4, repMin: 10, repMax: 10, unit: 'kg_side', increment: 2.5, type: 'primary' },
  { id: 'ex_straight_arm_pulldown', catalogId: 'cat_straight_arm_pulldown', templateId: 'upperB', name: 'Cable straight-arm pulldown', sets: 3, repMin: 12, repMax: 12, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_machine_reverse_fly', catalogId: 'cat_machine_reverse_fly', templateId: 'upperB', name: 'Machine reverse fly', sets: 3, repMin: 12, repMax: 12, unit: 'kg_total', increment: 2.5, type: 'accessory' },
  { id: 'ex_db_curls', catalogId: 'cat_db_curls', templateId: 'upperB', name: 'DB curls', sets: 3, repMin: 12, repMax: 12, unit: 'kg_side', increment: 1, type: 'accessory' },
  { id: 'ex_farmers_walk', catalogId: 'cat_farmers_walk', templateId: 'upperB', name: "Farmer's walk", sets: 3, repMin: 1, repMax: 1, unit: 'kg_side', increment: 2.5, type: 'accessory', measure: 'laps' },
  { id: 'ex_row_1km_ub', catalogId: 'cat_row_1km', templateId: 'upperB', name: 'Row 1 km', sets: 1, repMin: 0, repMax: 0, unit: 'none', increment: 0, type: 'conditioning', measure: 'seconds' },
];

const orderCounters: Record<string, number> = {};

export const SEED_EXERCISES: Exercise[] = raw.map((e) => {
  const order = orderCounters[e.templateId] ?? 0;
  orderCounters[e.templateId] = order + 1;
  return {
    ...e,
    order,
    measure: e.measure ?? 'reps',
    perSide: e.perSide ?? false,
    archived: false,
  };
});

/**
 * Seed exercise id -> catalogue id. The v2 upgrade uses this to link exercises
 * created before the catalogue existed; several seed rows share one catalogue
 * entry (both "Leg curl"s, both "Calf raises", both "Row 1 km"s).
 */
export const SEED_EXERCISE_TO_CATALOG: Record<string, string> = Object.fromEntries(
  raw.map((e) => [e.id, e.catalogId]),
);
